[package]
name = "vrc_speech_to_chatbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vosk = "0.2.0"
cpal = "0.14.2"
rosc = "0.9.1"
dasp = "0.11.0"
